apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: node-automation-rules-engine
  labels:
    app: node-automation-rules-engine
    env: staging
spec:
  selector:
    matchLabels:
      app: node-automation-rules-engine
  template:
    metadata:
      labels:
        app: node-automation-rules-engine
    spec:
      containers:
      - name: node-automation-rules-engine
        image: gcr.io/decoded-agency-207514/automation-rules-engine:IMAGE_TAG
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        env:
        - name: NODE_ENV
          value: staging
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 400m
            memory: 500Mi
