# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   namespace: staging
#   name: node-automation-rules-engine
#   labels:
#     env: staging
#   annotations:
#     kubernetes.io/ingress.class: "gce"
#     kubernetes.io/ingress.global-static-ip-name: "automation-rules-engine-staging-ip"
#     kubernetes.io/ingress.allow-http: "true"
# spec:
#   tls:
#   - hosts:
#     - automation-rules-engine-staging.workiz.com
#     secretName: workiz-nginx 
#   rules:
#     - host: automation-rules-engine-staging.workiz.com
#       http:
#         paths:
#         - path: /*
#           backend:
#             serviceName: node-automation-rules-engine
#             servicePort: 9090