apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: node-automation-rules-engine
  labels:
    service: node-automation-rules-engine
    env: staging
    cluster-service: "true"
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - name: https
    protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app: node-automation-rules-engine